spring:
    application:
        name: oasis-hotels-api

    datasource:
        url: jdbc:mysql://localhost:3308/oasis_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "format_sql": true
        # 💡 LÍNEA NUEVA: Espera a que Hibernate termine de crear las tablas antes de insertar datos
        defer-datasource-initialization: true

    # 💡 LÍNEAS NUEVAS: Le dice a Spring que ejecute el archivo data.sql
    sql:
        init:
            mode: always
    
    mvc:
        problemdetails:
            enabled: true

server:
    port: 8001