spring:
  datasource:
    # Here we use 'localhost' because your IDE is outside the Docker network.
    # It connects through the mapped port (3308) from your docker-compose.
    url: jdbc:mysql://localhost:3308/oasis_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties:
      hibernate:
        format_sql: true 
        highlight_sql: true 
        
  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG 
    org.hibernate.SQL: DEBUG